site_name: LHobby

repo_url: https://github.com/manudarmi/DistributedProgrammingLHobby
repo_name: "Github: LHobby"

use_directory_urls: true

docs_dir: markdown

extra_css: [ assets/css/badge.css ]

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
#    - toc.integrate
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
  - footnotes
  - attr_list
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction:
      - LHobby: 'introduction/index.md'
      - Installation: 'introduction/installation.md'
      - Usage: 'introduction/usage.md'
  - 'External dependencies': 'external-dependencies/index.md'
  - Architecture:
      - 'Architecture overview': 'architecture/index.md'
  - Interfaces and protocols:
      - 'REST API': 'interfaces/rest-api.md'
      - 'Websockets': 'interfaces/websockets.md'
  - 'Code description and examples':
      - 'Project structure': 'code-description-and-examples/index.md'
      - 'REST API': 'code-description-and-examples/rest-api.md'
      - 'Pong inner workings': 'code-description-and-examples/game.md'
