# Generated by Django 3.1.3 on 2020-11-29 12:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201129_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmatch',
            name='loser_elo_after_match',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedmatch',
            name='loser_elo_before_match',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedmatch',
            name='loser_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedmatch',
            name='winner_elo_after_match',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedmatch',
            name='winner_elo_before_match',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedmatch',
            name='winner_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='completedmatch',
            constraint=models.CheckConstraint(check=models.Q(winner_score__gt=django.db.models.expressions.F('loser_score')), name='check_scores'),
        ),
        migrations.AddConstraint(
            model_name='completedmatch',
            constraint=models.CheckConstraint(check=models.Q(winner_elo_before_match__lte=django.db.models.expressions.F('winner_elo_after_match')), name='check_winner_elo'),
        ),
        migrations.AddConstraint(
            model_name='completedmatch',
            constraint=models.CheckConstraint(check=models.Q(loser_elo_before_match__gte=django.db.models.expressions.F('loser_elo_after_match')), name='check_loser_elo'),
        ),
        migrations.AddConstraint(
            model_name='completedmatch',
            constraint=models.CheckConstraint(check=models.Q(completion_timestamp__gt=django.db.models.expressions.F('start_timestamp')), name='check_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='ongoingmatch',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_started', True), ('is_challenger_ready', True)), models.Q(('is_started', False), ('is_challenger_ready', False)), models.Q(('is_started', False), ('is_challenger_ready', True)), _connector='OR'), name='check_state'),
        ),
    ]
