# Generated by Django 3.1.3 on 2020-11-29 16:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20201129_1336'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='completedmatch',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, winner=django.db.models.expressions.F('loser')), name='check_cant_play_alone'),
        ),
    ]
