site_name: LHobby

repo_url: https://github.com/manudarmi/DistributedProgrammingLHobby
repo_name: "Github: LHobby"

use_directory_urls: false

docs_dir: markdown

theme:
        name: material
        features:
                - navigation.tabs
                - navigation.instant
                - toc.integrate
        icon:
                repo: fontawesome/brands/github
markdown_extensions:
        - admonition
        - pymdownx.superfences
        - pymdownx.highlight:
                linenums: true
        - pymdownx.keys
        - pymdownx.inlinehilite
        - pymdownx.tabbed
        - footnotes
        - attr_list
        - toc:
              toc_depth: 3

nav:
        - Introduction:
                  - LHobby: 'introduction/index.md'
                  - Installation: 'introduction/installation.md'
                  - Usage: 'introduction/usage.md'
        - 'External dependencies': 'external dependencies/index.md'
        - Architecture:
                  - 'Overview': 'architecture/index.md'
        - Interfaces:
                  - 'REST API': 'interfaces/REST_API.md'
                  - 'Websockets': 'interfaces/websockets.md'
        - 'Relevant code description':
                  - Overview: 'relevant code description/index.md'